export const initialState = {
          loading: false,
          submit:true,
          selectedMachineId: undefined,
          selectedAttachedMachineryId: undefined,
          selectedLocationId: undefined,
          selectedFarmId: undefined,
          selectedProductId: undefined,
          selectedOperatorId: undefined,
          kilometersOnMachine: undefined,
          liters: undefined,
          tankNum:undefined,
          timeOfEntry: undefined,
          explainTheActivity: undefined,
          workedHours: undefined,
          manHours: undefined,
          selectedMachineMaintenanceId: undefined,
          selectedMaintenanceId: undefined,
          selectedTechnicianId: undefined,
          selectedTypeOfHoursId: undefined,
          selectedProjectId: undefined,
          selectedMSJobDescriptionId: undefined,
          disableMultiSelectOption: false ,
          selectedSpendingOrPurchaseId: false,
          selectedLocationName: undefined,
          selectedMachineName: undefined,
          selectedMachinesJobsId: undefined,
          machinesJobs: undefined,
          quantity: undefined,
          price: undefined,
          purposeOfPurchase: undefined,
          selectedSupplierId: undefined,
          selectedCategoryOfMaterialsId: undefined,
          selectedSubcategoryOfMaterialsId: undefined,
          supplier: undefined,
          selectedSupplierOfFuelId: undefined
}